<?php declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Robchett\Aoc2024\Task;

final class Day8Test extends TestCase
{
    public function testPart1(): void
    {
        $input = <<<input
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
        input;
        /** @var Task $runner */
        $runner = require __DIR__ . '/../src/day8.php';
        $res = $runner->task1();
        $this->assertSame(14, $res->unwrap());
    }

    public function testPart2(): void
    {
        $input = <<<input
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
        input;
        /** @var Task $runner */
        $runner = require __DIR__ . '/../src/day8.php';
        $res = $runner->task2();
        $this->assertSame(34, $res->unwrap());
    }
}